// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agdskvhbmbpowwqyfanr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZHNrdmhibWJwb3d3cXlmYW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTQ1NjEsImV4cCI6MjA2NjEzMDU2MX0.cvBnDFd6flGlB4jXMT4jHefHzr__svn0Kivt4eONExE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);